### ISSUE TITLE
TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by Jezzkis** [oelin/midjourney-client#1]
I'm using the API for a chatbot on whastapp. It was working until some time ago. After that it just returns TypeError [ERR_INVALID_URL]: Invalid URL
![imagem_2023-02-12_105227515](https://user-images.githubusercontent.com/81809570/218315028-64d2d3d1-08f7-4c6b-9b11-21fb6270c4c2.png)

![image](https://user-images.githubusercontent.com/81809570/218315108-9a4babe6-b450-4ba4-bcb4-b805abd0b0c4.png)

Thanks

**Comment by oelin** [comment]
I haven't been able to reproduce this error. I checked to see if `midjourney("...", { width: 1024 })` was the issue but it seems to be working. Note that the client returns an array of URLs. In your code you don't explicitly index into that array, so maybe that's the issue? Try:

```js
const media = await MessageMedia.fromUrl(imageJourney[0])
```

**Comment by Jezzkis** [comment]
find out the problem. Apparently MidJourney if you make a lot of requests it gives you an IP ban. I used a VPN and it worked again. 
must be some anti-spam method

Thanks @oelin <3
