### ISSUE TITLE
Sign-in required

### ISSUE THREAD

**Issue by philszalay** [oelin/midjourney-client#11]
The client was working flawless until an error was thrown on every request. As can be seen in the screenshots it looks like an authentication problem.
Is it my fault or what is went wrong here?

![Screenshot 2023-04-13 at 19 11 47](https://user-images.githubusercontent.com/12916001/231834564-982c3eff-eec1-4718-9b39-ab742abae062.png)
![Screenshot 2023-04-13 at 19 10 46](https://user-images.githubusercontent.com/12916001/231834570-47d1fb7f-0176-4754-89cd-7331bcba6138.png)

**Comment by oelin** [comment]
I'm looking into this, however I beleive it may have to do with Replicate's rate limiting. They haven't provided much information on how rate limiting is applied to public models. For now, I would recommend not making too many requests per hour.

**Comment by sromovskypeter** [comment]
It is not related to rate limiting.
