### ISSUE TITLE
the program just stopped after it's done, it didn't return anything or provide any error code

### ISSUE THREAD

**Issue by BarryAllen-Arrow** [oelin/midjourney-client#13]
I have this code
`import midjourney from "midjourney-client"

await midjourney("mdjrny-v4 style a painting of a ginger cat.")`

And I run it in my powershell window like this: 
`node test.js`

and then it just end, without returning anything

**Comment by oelin** [comment]
Try this:

```js
import midjourney from "midjourney-client"

const imageURLs = await midjourney("mdjrny-v4 style a painting of a ginger cat.")

console.log(imageURLs)
```

**Comment by BarryAllen-Arrow** [comment]
thx! It's working!!
