### ISSUE TITLE
Can't generate a 1024x1024 image

### ISSUE THREAD

**Issue by nascarjake** [oelin/midjourney-client#2]
Hi there, I've run this command and it returns a blank array. If i dont send an image size I get a result but its small.
Ive also tried changing the number of iterations and i did get a wider picture to render with 20 iterations but if i make it a square image at 1024x1024 even putting the integrations down to 5 still wont generate the image on time.

I assume its part of some timeout - and I assume I probably wont be able to generate the images I want with this library. Been trying to find a solution for midjourney but its like jumping through hoops. Using Dalle2 right now via api and its just terrible.

Any suggestions would be greatly appreciated

console.log(await midjourney('a painting of a ginger cat.', {width: 1024, height: 1024, num_inference_steps: 5}))

**Comment by oelin** [comment]
On the Replicate API documentation for Openjourney, it says that the maximum size permitted for generated images is 1024x768 or 768x1024. https://replicate.com/prompthero/openjourney/api#inputs. I'll add this information to the README soon.
