### ISSUE TITLE
cant get an image to upload on basic html page.

### ISSUE THREAD

**Issue by bsegelke** [oelin/midjourney-client#5]
Hello there, this mistake is probably my bad, but id love to figure out how to integrate this into my app. I've tried just getting an image to render to my html preview page, but doesnt seem to be registering, not sure if im missing a step or what. here's my html page.

`<!DOCTYPE html>
<html>
  <head>
    <title>Displaying an Image Fetched by midjourney Function</title>
  </head>
  <body>
    <h1>Image Fetched by midjourney Function</h1>
    <img id="catImage">
    
    <script src="script.js"></script>
  </body>
</html>`

And heres what i have for my javascript file, yet not getting anything.
`async function displayCatImage() {
  try {
    const imageURL = await midjourney('mdjrny-v4 style a painting of a ginger cat.');
    console.log(imageURL);
    const catImage = document.getElementById('catImage');
    catImage.src = imageURL;
  } catch (error) {
    console.error(error);
  }
}

displayCatImage();`

**Comment by oelin** [comment]
The client only works **server-side** using `node-fetch` behind the scenes. If you'd like to use it within your app, I recommend creating an API route for it (e.g. using [Express](https://expressjs.com/)) and then calling that from your front-end.

**Comment by bsegelke** [comment]
copy that, that makes sense! And I wont need an API key to make it work either?
Any chance you have any example projects youve made using it, I could take a glance at?
Thank by the way!
